### ISSUE TITLE
Do I have to run the rviz visualization node when running the scenario simulator?

### ISSUE THREAD

**Issue by Zoe-Wan** [tier4/scenario_simulator_v2#1014]
Thanks for your excellent work, it helps me a lot. I want to implement a automatic disturbance generation of perception data node with the scenario simulator, which needs to run the scenario simulator many times. I notice that running rviz occupies most of experience time. So I wonder if I can run the scenario simulator without rviz node?

**Comment by hakuturu583** [comment]
Sorry for my late reply.
Yes, you can do it.
Please run with [launch_rviz option](https://github.com/tier4/scenario_simulator_v2/blob/1ecd0302cc707fa9b21de93826c5cdd39f809e3b/test_runner/scenario_test_runner/launch/scenario_test_runner.launch.py#L69) with False.
