### ISSUE TITLE
scenario_test_runner seems not killing rviz

### ISSUE THREAD

**Issue by hayato-m126** [tier4/scenario_simulator_v2#1015]
**Describe the bug**

When I launch a scenario with scenario_test_runner, multiple rviz processes remain.
Running the following command will leave 3 rviz processes.

https://tier4.github.io/scenario_simulator_v2-docs/user_guide/QuickStart/#scenario_test_runner

```shell
ros2 launch scenario_test_runner scenario_test_runner.launch.py architecture_type:=awf/universe record:=false scenario:='$(find-pkg-share scenario_test_runner)/scenario/sample.yaml' sensor_model:=sample_sensor_kit vehicle_model:=sample_vehicle
```

**To Reproduce**
1. build latest autoware foundation's autoware
2. ros2 launch scenario_test_runner scenario_test_runner.launch.py architecture_type:=awf/universe record:=false scenario:='$(find-pkg-share scenario_test_runner)/scenario/sample.yaml' sensor_model:=sample_sensor_kit vehicle_model:=sample_vehicle
3. run process monitor

**Expected behavior**
Rviz process is killed properly every time.

**Screenshots**
![Chrome リモート デスクトップ - dpc1909014-2204_002](https://github.com/tier4/scenario_simulator_v2/assets/16977736/0e94f7bb-dfb6-4446-aaa4-b96ff39ad8cd)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser Chrome
 - ROS 2 Humble
 - DDS Cyclone DDS

**Comment by villaoningfootball** [comment]
I also encountered the same problem. Please how to solve? thank you

**Comment by J-xinyu** [comment]
Me too...

**Comment by hayato-m126** [comment]
A tentative solution is to increase the value of `timeout.tv_sec`

https://github.com/tier4/scenario_simulator_v2/blob/master/external/concealer/src/field_operator_application.cpp#L103

**Comment by hakuturu583** [comment]
Do you have any idea of this behaviour?
I git blamed the relevant business and it seems that it was last edited by @yamacir-kit.

https://github.com/tier4/scenario_simulator_v2/blame/master/external/concealer/src/field_operator_application.cpp#L103

**Comment by yamacir-kit** [comment]
I know how to fix it, but I don't have time to fix it.

**Comment by villaoningfootball** [comment]
> I know how to fix it, but I don't have time to fix it.

we need you
