### ISSUE TITLE
Documentation link error

### ISSUE THREAD

**Issue by hakuturu583** [tier4/scenario_simulator_v2#1035]
**Describe the bug**
Image was not shown.

**To Reproduce**
Open [this URL](https://tier4.github.io/scenario_simulator_v2-docs/user_guide/QuickStart/#random_test_runner).

**Expected behavior**
The image was shown.

**Screenshots**
![Screenshot from 2023-07-19 17-49-43](https://github.com/tier4/scenario_simulator_v2/assets/10348912/41420725-4c9f-40d1-b654-d1f78f434333)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser: chrome

**Comment by f0reachARR** [comment]
This link seems just a link, not a link with image. But image syntax is used.

https://github.com/tier4/scenario_simulator_v2/blob/5329ddad3e31f1528caf55cf50253db9db34b613/docs/user_guide/QuickStart.md?plain=1#L83
