### ISSUE TITLE
Scenario simulator can't work on arm64 architecture

### ISSUE THREAD

**Issue by oguzkaganozt** [tier4/scenario_simulator_v2#1094]
**Describe the bug**
Embree package is not available for arm64 architecture, the scenario simulator can't work on arm64 architectures

**To Reproduce**
```
vcs import src < simulator.repos
./setup-dev-env.sh
source /opt/ros/humble/setup.bash
rosdep install -iry --from-paths src --rosdistro $ROS_DISTRO
```

**Expected behavior**
Successful Rosdep installation

 - Platform: Ubuntu22.04 - ROS2 Humble - arm64

**Comment by hakuturu583** [comment]
Thank you for reporting.
ARM support is discussed at the maintainers' meeting.

**Comment by hakuturu583** [comment]
Thanks, currently we are trying to send patch to embree_vendor package and trying to fix this problem.

**Comment by hakuturu583** [comment]
Start adding build test on ARM CPUs using qemu.
However, integration test does not provide on ARM CPUs.

**Comment by hakuturu583** [comment]
I close this pull request, but if you need integration test on ARM CPU or other features.
Please re-open this pull request.
