### ISSUE TITLE
Failure of recording a scenario simulation

### ISSUE THREAD

**Issue by lethal233** [tier4/scenario_simulator_v2#1179]
**Describe the bug**

The scenario simulator cannot perform normally when I set the `record` to true, which means:
1. it cannot do the scenario test simulation
2. it cannot record the simulation.

**To Reproduce**
1. Run the scenario test simulation with the command `ros2 launch scenario_test_runner scenario_test_runner.launch.py   architecture_type:=awf/universe record:=false scenario:='t4v2.yml'   sensor_model:=sample_sensor_kit   vehicle_model:=sample_vehicle`
2. The scenario is simulated and played on the rviz.
3. Run the scenario test simulation again with the command `ros2 launch scenario_test_runner scenario_test_runner.launch.py   architecture_type:=awf/universe record:=true scenario:='t4v2.yml'   sensor_model:=sample_sensor_kit   vehicle_model:=sample_vehicle`
5. Rviz is successfully started, but the scenario is not simulated, along with console error output.

**Expected behavior**

The scenario test simulator should run the scenario normally and record the whole simulation messages.

**Screenshots**

![image](https://github.com/tier4/scenario_simulator_v2/assets/47763046/e713b29e-5629-4a7b-bf6d-48cd5c3b7f12)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - ROS 2 version: humble

The file is attached here: https://drive.google.com/file/d/1LDSyvA9PUEf58OzcS4sJ-3XLTVgAnOPJ/view?usp=drive_link

**Comment by hakuturu583** [comment]
As we infer from the error text, it is probably an error in the DDS communication process.
It may be cured by reviewing the DDS communication settings, etc.

**Comment by lethal233** [comment]
Got it, I will try to inspect the DDS settings first.

**Comment by lethal233** [comment]
@hakuturu583 Thanks, after configuring the DDS settings I can record and replay the scenario mentioned above successfully. But there is another issue, when I replay the rosbag file, the steering angle and speed were not displayed. I also tried the sample file from https://autowarefoundation.github.io/autoware-documentation/main/tutorials/ad-hoc-simulation/rosbag-replay-simulation/, and there was also no such information. Screenshot is attached.
![image](https://github.com/tier4/scenario_simulator_v2/assets/47763046/dda45f19-b06f-4288-a9f1-c30a2314a14a)
