### ISSUE TITLE
Parameter 'timeout' has invalid type Error  in docs/tutorials/RunWithDocker.md

### ISSUE THREAD

**Issue by xczhanjun** [tier4/scenario_simulator_v2#700]
**Parameter 'timeout' has invalid type Error  in doccs/tutorials/RunWithDocker.md**

[traffic_simulation_demo-1] terminate called after throwing an instance of 'rclcpp::exceptions::InvalidParameterTypeException'
[traffic_simulation_demo-1]   what():  parameter 'timeout' has invalid type: Wrong parameter type, parameter {timeout} is of type {double}, setting it to {integer} is not allowed.

**To Reproduce**
 rocker --x11 tier4/scenario_simulator_v2:galactic ros2 launch cpp_mock_scenarios mock_test.launch.py scenario:=crashing_npc scenario:=traffic_simulation_demo launch_rviz:=true timeout:=60

**Comment by hakuturu583** [comment]
Thank you for checking our mistake!
I will fix soon!

**Comment by hakuturu583** [comment]
This problem was solved by #715
