### ISSUE TITLE
The console_scripts of  openscenario_utility can not work ('xmlschema==1.3.1 is required)

### ISSUE THREAD

**Issue by xczhanjun** [tier4/scenario_simulator_v2#701]
**openscenario_utility can not work**

**To Reproduce**

the Docker image is :
"RepoDigests": [
            "tier4/scenario_simulator_v2@sha256:28f243daba2789b7de5d64e43c0d9fce812e782d7a26adea1383bed41b1d1e1f",
]

root@ee6a88b77a77:/home/ubuntu/Desktop/scenario_simulator_ws/install/openscenario_utility/lib/openscenario_utility# ./yaml2xosc 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./yaml2xosc", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 787, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'xmlschema==1.3.1' distribution was not found and is required by openscenario-utility

**Comment by hakuturu583** [comment]
Thank you!
I will check.

**Comment by hakuturu583** [comment]
Is this happening in the current master branch?

**Comment by hakuturu583** [comment]
This issue seems no longer active.
Please reopen this issue, if necessary.
