### ISSUE TITLE
THE tier4_msgs version is different with autoware.universe 

### ISSUE THREAD

**Issue by xczhanjun** [tier4/scenario_simulator_v2#730]
**Describe the bug**
---
https://github.com/autowarefoundation/autoware/blob/main/autoware.repos
universe/tier4_autoware_msgs:
    type: git
    url: https://github.com/tier4/tier4_autoware_msgs.git
    version: tier4/universe
---
https://github.com/tier4/scenario_simulator_v2/blob/master/dependency_galactic.repos
  tier4_msgs:
    type: git
    url: https://github.com/tier4/AutowareArchitectureProposal_msgs.git
    version: tier4/universe # for Autoware.Unvierse (Tier IV)

**Comment by hakuturu583** [comment]
It seems it just a old name.
But I will rewrite to new URL.
Thanks.

**Comment by hakuturu583** [comment]
This problem was solved by #742
