### ISSUE TITLE
Support for traffic lights in scenario editor

### ISSUE THREAD

**Issue by soblin** [tier4/scenario_simulator_v2#782]
I'm trying to create a scenario that includes traffic light recognition. As you may know,  we can set traffic light status by using [this rviz panel](https://github.com/autowarefoundation/autoware.universe/tree/main/common/tier4_traffic_light_rviz_plugin) in planning simulator. But I cannot find traffic light functionality in scenario editor as of know.

I think using this [TrafficSignalControllerAction file](https://github.com/tier4/scenario_simulator_v2/blob/master/test_runner/scenario_test_runner/scenario/TrafficSignalControllerAction.yaml) is one solution, but would appreciate it if I could set traffic light status like the rviz_panel on scenario editor too.

**Comment by yamacir-kit** [comment]
@soblin 
The definition of the traffic light by the scenario editor is currently being implemented, so please be patient.
