### ISSUE TITLE
The ports used by `simple_sensor_simulator` may interfere with other software

### ISSUE THREAD

**Issue by HansRobo** [tier4/scenario_simulator_v2#907]
`simple_sensor_simulator` defaultly uses the ports which is included in [well-known used ports list](https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers)
⇒TCP port No. 5555,5556

https://github.com/tier4/scenario_simulator_v2/blob/5d7c674944785baab6a31e88a65aa544b99fb4b8/simulation/simulation_interface/include/simulation_interface/constants.hpp#L34-L45

**Comment by hakuturu583** [comment]
Thanks, #981 changed the port.
Currently, we use only 5555.
