### ISSUE TITLE
please refer offisial documentation of ScenarioEditor 

### ISSUE THREAD

**Issue by HansRobo** [tier4/scenario_simulator_v2#995]
**Is your feature request related to a problem? Please describe.**

scenario_simulator_v2 documentation includes (outdated?) ScenarioEditor documentation

**Describe the solution you'd like**

refer [Web.Auto documentation](https://docs.web.auto/user-manuals/scenario-editor/introduction)

**Comment by hakuturu583** [comment]
I think it is a good idea, but this document is japanese.
I will search english version.

**Comment by hakuturu583** [comment]
I found [it.](https://docs.web.auto/en/user-manuals/scenario-editor/introduction)

**Comment by hakuturu583** [comment]
@HansRobo I did not check well, but it seems some of the documentation was deleted.

**Comment by HansRobo** [comment]
@HansRobo 
I cannot judge whether "some of the documentation was deleted" itself is bad or not.
But, I was advised to replace it by TIER IV CI/CD team, so I think it's better to replace it.

**Comment by HansRobo** [comment]
@hakuturu583 
I cannot judge whether "some of the documentation was deleted" itself is bad or not.
But, I was advised to replace it by TIER IV CI/CD team, so I think it's better to replace it.

**Comment by hakuturu583** [comment]
@HansRobo I agree.
I will ask to CI/CD team.

**Comment by HansRobo** [comment]
close with #1036
